### ISSUE TITLE
Fix Getting Started Link

### ISSUE THREAD

**Issue by curran** [IPWright83/chart-io#138]
The "Getting Started" link seems broken:

https://ipwright83.github.io/chart-it/?path=/story/introduction--page

I see this:

![image](https://github.com/IPWright83/chart-it/assets/68416/64ad8999-5ab1-4a00-9023-2fc2d2540353)

**Comment by IPWright83** [comment]
Thanks for reporting @curran. I've updated the link in the repo, though I've not triggered a new publish so any Readme on npm may be out of date till my next release as I can't run the required CLI command on my phone 😔
